<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/1_2_N%EC%B0%A8%EC%9B%90_%EB%B0%B0%EC%97%B4%EC%9D%98_%EB%8D%B0%EC%9D%B4%ED%84%B0_%ED%83%80%EC%9E%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3], dtype=np.float)
print(arr, arr.dtype)

[1. 2. 3.] float64


In [ ]:
arr = np.array([1.1,2.2,3.3], dtype=np.int)
print(arr, arr.dtype)

[1 2 3] int64


In [ ]:
arr = np.array([0, 1, 1], dtype=np.bool)
print(arr, arr.dtype)

[False  True  True] bool


In [ ]:
arr = np.array([0,1,2,3])
print(arr, arr.dtype)

arr = arr.astype(np.float32)
print(arr, arr.dtype)

[0 1 2 3] int64
[0. 1. 2. 3.] float32


In [ ]:
# 데이터 타입이 혼재하는 경우
arr = np.array([1, 2, 3.4])
print(arr, arr.dtype)

[1.  2.  3.4] float64


In [ ]:
# 데이터 타입이 혼재하는 경우
arr = np.array([1, 2, 3.4, "64"]) # 문자 = 유니코드
print(arr, arr.dtype)

['1' '2' '3.4' '64'] <U32


In [ ]:
# 데이터 타입이 혼재하는 경우
arr = np.array([1, 2, 3.4, "64"], dtype=int)
print(arr, arr.dtype)

[ 1  2  3 64] int64


In [ ]:
# 데이터 타입이 혼재하는 경우
arr = np.array([1, 2, 3.4, "64"], dtype=int)
print(arr, arr.dtype)