<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/2_1_%EB%B0%B0%EC%97%B4%EC%9D%98_index_%EC%A0%91%EA%B7%BC%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 1차원 배열
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(arr[3])
print(arr[1])
print(arr[-1])
print(arr[-3])
print(arr[-10])

3
1
9
7
0


In [ ]:
# 2차원 배열
arr1 = np.array([[1,2,3,4]
                 ,[5,6,7,8]
                 ,[9,10,11,12]])
               
print(arr1, arr1.shape, arr1.ndim)

# 4라는 원소에 접근
print(arr1[0][3]) # 0행에 해당하는 3번째 값
print(arr1[0, 3]) # 0행에 해당하는 3번째 값

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 2
4
4


In [ ]:
# 1차원 배열에서의 범위 값 탐색
arr = np.array([0,1,2,3,4,5,6,7,8,9])
# 3 ~8미만 까지의 값 탐색
print(arr[3:8])
# 3 ~ 끝까지 값 탐색
print(arr[3:])


print(arr[:7])
print(arr[:-1])

[3 4 5 6 7]
[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8]


In [ ]:
# 2차원 배열에서의 범위 값 탐색
arr = np.array([[1,2,3,4]
                ,[5,6,7,8]
                ,[9,10,11,12]])
# 특정값 출력 : 0행값 모두 출력
print(arr[0, :])
# 특정 열의 값 출력
print(arr[:, 1])

[1 2 3 4]
[ 2  6 10]


In [ ]:
# 모든 원소 출력
print(arr[:3, :])
print(arr[:2, 2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]
