<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/2_3_Boolean_%EC%9D%B8%EB%8D%B1%EC%8B%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 1차원
arr = np.array([1,2,3,4])
print(arr[[True, False, True, True]])

[1 3 4]


In [ ]:
# 2차원
arr = np.array([[1,2,3,4]
                ,[5,6,7,8]])

# 행은 1행만 가져오고, 열은 전부다 가져온다.
print(arr[[True,False], True])

[[1 2 3 4]]


In [ ]:
# 2차원
# 조건 연산자를 이용하여 값을 가져오기
arr = np.array([[1,2,3,4]
                ,[5,6,7,8]])
print(arr[arr > 4])
print(arr[arr > 3])
print(arr[arr <=2])
print(arr[arr >= 4])

[5 6 7 8]
[4 5 6 7 8]
[1 2]
[4 5 6 7 8]
