<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/3-5%20%EB%B8%8C%EB%A1%9C%EB%93%9C%EC%BA%90%EC%8A%A4%ED%8C%85(Broadcasting).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# shape이 다른 두 ndarray의 연산 실행하기
arr1 = np.array([[0, 0, 0],
                 [1, 1, 1],
                 [2, 2, 2]])
arr2 = np.array([[5, 6, 7]])

print(arr1 + arr2)

arr1 = np.array([[1, 1, 1]])
arr2 = np.array([[0],
                 [1],
                 [2]])
print(arr1 + arr2)

arr1 = np.array([[1, 1, 1]])
arr2 = np.array([[1]])

print(arr1 + arr2)        

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[2 2 2]]
