<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/4-1%201%EC%B0%A8%EC%9B%90%20%EB%B0%B0%EC%97%B4%EC%9D%98%20%EC%A0%95%EB%A0%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(10, size=10) # 10개 뽑기
print(arr)

[2 0 6 9 9 1 8 7 1 7]


In [ ]:
# 오름차순
print(np.sort(arr))

[0 1 1 2 6 7 7 8 9 9]


In [ ]:
# 내림차순
print(np.sort(arr)[::-1]) # 인덱싱 : 처음부터 끝까지 -1칸 간격으로

[9 9 8 7 7 6 2 1 1 0]


In [ ]:
# 값 들을 유지하기
arr = np.sort(arr)
print(arr)
arr.sort()
print(arr)

[0 1 1 2 6 7 7 8 9 9]
[0 1 1 2 6 7 7 8 9 9]
