<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/4-2%202%EC%B0%A8%EC%9B%90%20%EB%B0%B0%EC%97%B4%EC%9D%98%20%EC%A0%95%EB%A0%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(15, size=(3,4)) # 15미만까지 3,4 배열 생성
print(arr)

[[ 2 10 10 13]
 [ 6  6  4 12]
 [ 7  9  5 12]]


In [ ]:
# 행을 기준으로 정렬
print(np.sort(arr))

[[ 2 10 10 13]
 [ 4  6  6 12]
 [ 5  7  9 12]]


In [ ]:
# 열을 기준으로 정렬
print(np.sort(arr, axis=0))

[[ 2  6  4 12]
 [ 6  9  5 12]
 [ 7 10 10 13]]


In [ ]:
# 2차원 배열을 1차원 배열로 변환해서 오름차순으로 정렬
print(np.sort(arr, axis=None))

[ 2  4  5  6  6  7  9 10 10 12 12 13]


In [ ]:
# argsort() 
# 원소가 정렬되었을때 정렬된 원소의 원래배열에서의 index를 반환
print(np.sort(arr, axis=1))
print(np.argsort(arr, axis=1))

[[ 2 10 10 13]
 [ 4  6  6 12]
 [ 5  7  9 12]]
[[0 1 2 3]
 [2 0 1 3]
 [2 0 1 3]]


In [ ]:
# argsort() 
# 원소가 정렬되었을때 정렬된 원소의 원래배열에서의 index를 반환
print(np.sort(arr, axis=0))
print(np.argsort(arr, axis=0))

[[ 2  6  4 12]
 [ 6  9  5 12]
 [ 7 10 10 13]]
[[0 1 1 1]
 [1 2 2 2]
 [2 0 0 0]]
