<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/5-1%20%EB%B0%B0%EC%97%B4%EC%9D%98%20%ED%98%95%ED%83%9C%20%EB%B3%80%EA%B2%BD1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# reshape : 배열의 형태 변경
arr = np.arange(12)
print(arr, arr.ndim)
print("="*30)

# 2차원
arr = arr.reshape(3, 4) # 원소의 size가 맞지 않으면 Error가 뜬다.
print(arr, arr.ndim)
print("="*30)

# 3차원 tensor
arr = arr.reshape(2, 3, 2)
print(arr, arr.ndim)
print("="*30)

# 4차원
arr = arr.reshape(2, 2, 1, 3)
print(arr, arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 2
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 3
[[[[ 0  1  2]]

  [[ 3  4  5]]]


 [[[ 6  7  8]]

  [[ 9 10 11]]]] 4


Curse of Dimensionality
차원의 저주
- 차원이 증가하면서 학습 데이터수가 차원의 수보다 적어지면서 모델의 성능이 저하되는 현상