<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/5-3%20%EB%B0%B0%EC%97%B4%EC%9D%98%20%ED%98%95%ED%83%9C%20%EB%B3%80%EA%B2%BD3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# expand_dims() : 입력한 axis값을 기준으로 차원을 추가하는 함수
arr = np.array([1, 2])
print(arr, arr.shape)
print('='*40)

# row값을 기준으로 차원을 추가
arr = np.expand_dims(arr, axis=0)
print(arr, arr.shape)
print('='*40)

# column값을 기준으로 차원을 추가
arr = np.expand_dims(arr, axis=1)
print(arr, arr.shape)

[1 2] (2,)
[[1 2]] (1, 2)
[[[1 2]]] (1, 1, 2)


In [ ]:
# squeeze() : 배열의 축을 제거, 차원을 축소하는 함수
arr = np.array([[1, 2]])
print(arr, arr.shape, arr.ndim)
print('='*40)

# row값(x축)을 기준으로 차원 축소(제거)
arr = np.squeeze(arr, axis=0)
print(arr, arr.shape, arr.ndim)
print('='*40)

# 3차원 배열
arr = np.array([[[1],
                 [2],
                 [3]]])
print(arr, arr.shape, arr.ndim)
print('='*40)

# 3차원 배열을 2차원으로 차원 축소(제거)
arr = np.squeeze(arr, axis=0)
print(arr, arr.shape, arr.ndim)
print('='*40)

[[1 2]] (1, 2) 2
[1 2] (2,) 1
[[[1]
  [2]
  [3]]] (1, 3, 1) 3
[[1]
 [2]
 [3]] (3, 1) 2


In [ ]:
# 3차원의 배열을 y축을 기준으로 배열 제거
arr = np.array([[[1, 2, 3]]])
print(arr, arr.shape, arr.ndim)
print('='*40)

arr = np.squeeze(arr, axis=1)
print(arr, arr.shape, arr.ndim)
print('='*40)

# axis 값을 주지 않으면 행렬이든 어떤 Tensor든 1차원 배열로 차원을 축소한다.
arr = np.squeeze(arr)
print(arr, arr.shape, arr.ndim)

[[[1 2 3]]] (1, 1, 3) 3
[[1 2 3]] (1, 3) 2
[1 2 3] (3,) 1
