<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/1_1_N%EC%B0%A8%EC%9B%90_%EB%B0%B0%EC%97%B4_%EC%83%9D%EC%84%B1%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 1차원 배열
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [ ]:
# 2차원 배열 
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
type([1,2,3])

list

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
tpl = (4,5,6)
arr = np.array(tpl)
arr

array([4, 5, 6])

In [ ]:
lst = [1,2,3]
arr = np.array(lst)
lst

[1, 2, 3]

In [ ]:
# list 2차원 array
lst = [[1,2,3], [4,5,6]]
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# shape 배열의 형태 or 모양
arr1 = np.array([1,2,3])
arr2 = np.array([[1,2,3], [1,2,3]]) #행이 2개 열이 3개

print(arr1.shape, arr2.shape)

(3,) (2, 3)


In [ ]:
# 차원 ndim
print(arr1.ndim, arr2.ndim)

1 2


In [ ]:
# size
# arr1 = 원소 3개
# arr2 = 원소 6개
print(arr1.size, arr2.size)

3 6
