<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/1_3_%EC%A0%95%ED%95%B4%EC%A7%84_%ED%98%95%EC%8B%9D%EC%9D%98_N%EC%B0%A8%EC%9B%90_%EB%B0%B0%EC%97%B4_%EC%83%9D%EC%84%B1%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# np.zeros() 모든 원소들이 0으로된 배열을 생성
arr = np.zeros([2,2]) # shape
print(arr)

[[0. 0.]
 [0. 0.]]


In [ ]:
# np.ones() 모든 원소들이 1로된 배열을 생성
arr = np.ones([3, 5]) # shape
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# np.full() 모든 원소들이 지정된 fill value로 이루어진 배열을 생성
arr = np.full((2,3), 5)
print(arr)

[[5 5 5]
 [5 5 5]]


In [ ]:
# n행 열을 m
# np.eye() n by m을 가진 대각원소가 1인 행렬을 만듦 나머지 원소는 0
arr = np.eye(3,4, k=0) # k는 대각원소의 발생지점을 어느부분에 나타낼것인지 지정
print(arr)

arr = np.eye(3,4, k=1) # k는 대각원소의 발생지점을 어느부분에 나타낼것인지 지정
print(arr)

arr = np.eye(3,4, k=-1) # -1은 반대방향으로 시작

arr = np.eye(3) # n값과 m값이 모두 3으로 정방행렬로 나타냄
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 지정된 배열과 동일한 shape의 행렬로 만들어 주는 함수
arr = np.array([[1,2,3],
               [4,5,6]])

# np.zeros_like()
# 동일한 배열을 가진 행렬의 원소를 0으로 만들어 줄 수 있다. 
arr_z = np.zeros_like(arr)
print(arr_z)

[[0 0 0]
 [0 0 0]]


In [ ]:
# 지정된 배열과 동일한 shape의 행렬로 만들어 주는 함수
arr = np.array([[1,2,3],
               [4,5,6]])

# np.ones_like()
# 동일한 배열을 가진 행렬의 원소를 1으로 만들어 줄 수 있다. 
arr_z = np.ones_like(arr)
print(arr_z)

[[1 1 1]
 [1 1 1]]


In [ ]:
arr = np.array([[1,2,3],
               [4,5,6]])

# np.full_like()
# 동일한 배열을 가진 행렬의 원소를 1으로 만들어 줄 수 있다. 
arr_z = np.full_like(arr, 9)
print(arr_z)

[[9 9 9]
 [9 9 9]]
