<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/1_4_%ED%8A%B9%EC%A0%95_%EB%B2%94%EC%9C%84%EC%9D%98_%EA%B0%92%EC%9D%84_%EA%B0%80%EC%A7%80%EB%8A%94_N%EC%B0%A8%EC%9B%90_%EB%B0%B0%EC%97%B4_%EC%83%9D%EC%84%B1%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
lst = list(range(0,9,2))
print(lst)

[0, 2, 4, 6, 8]


In [ ]:
 arr = np.arange(9) # start
 print(arr)

[0 1 2 3 4 5 6 7 8]


In [ ]:
 arr = np.arange(3, 12) # start, stop
 print(arr)

[ 3  4  5  6  7  8  9 10 11]


In [ ]:
 arr = np.arange(3, 13, 3) # start, stop, step(간격)
 print(arr)

[ 3  6  9 12]


In [ ]:
 # 직접 입력도 가능

 arr = np.arange(start=0, stop=9, step=2) # start, stop, step(간격) / (0,9,2)
 print(arr)

[0 2 4 6 8]


In [ ]:
# np.linspace()
arr = np.linspace(0, 100, 100) # 0부터 100까지의 원소에 균등한 간격으로 배열생성
print(arr)

[  0.           1.01010101   2.02020202   3.03030303   4.04040404
   5.05050505   6.06060606   7.07070707   8.08080808   9.09090909
  10.1010101   11.11111111  12.12121212  13.13131313  14.14141414
  15.15151515  16.16161616  17.17171717  18.18181818  19.19191919
  20.2020202   21.21212121  22.22222222  23.23232323  24.24242424
  25.25252525  26.26262626  27.27272727  28.28282828  29.29292929
  30.3030303   31.31313131  32.32323232  33.33333333  34.34343434
  35.35353535  36.36363636  37.37373737  38.38383838  39.39393939
  40.4040404   41.41414141  42.42424242  43.43434343  44.44444444
  45.45454545  46.46464646  47.47474747  48.48484848  49.49494949
  50.50505051  51.51515152  52.52525253  53.53535354  54.54545455
  55.55555556  56.56565657  57.57575758  58.58585859  59.5959596
  60.60606061  61.61616162  62.62626263  63.63636364  64.64646465
  65.65656566  66.66666667  67.67676768  68.68686869  69.6969697
  70.70707071  71.71717172  72.72727273  73.73737374  74.74747475
  75.7575757

In [ ]:
# np.logspace()
arr = np.linspace(1, 10, 10)
print(arr, end="\n\n")

arr = np.logspace(1, 10, 10, base=2) # base = log의 밑값
print(arr)

arr = np.logspace(1, 10, 10) # base값을 입력하지 않으면 상용로그로 표시됨
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]
