<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/2_2_Fancy_%EC%9D%B8%EB%8D%B1%EC%8B%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 1차원 배열
arr = np.array([5, 10, 15, 20, 25, 30])
print(arr[[0,2,4]]) # 0번째 2번째 4번째 원소

[ 5 15 25]


In [ ]:
# 2차원 배열
arr = np.array([[5, 10, 15, 20]
                ,[25,30,35,40]
                ,[45,50,55,60]])

# 0행과 2행에 해당하는 값에 대해서 2열부터 끝까지
print(arr[[0, 2], 2:])

# 1행부터 끝까지 2열과 3열에 해당하는 값을 가져오겠다.
print(arr[1:, [2, 3]])

[[15 20]
 [55 60]]
[[35 40]
 [55 60]]
