<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/3_2_%EB%B0%B0%EC%97%B4%EC%9D%98_%EC%97%B0%EC%82%B02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 1차원 행렬
# 각각의 원소의 곱의 합이 결과가 된다. 
arr1 = np.array([2,3,4])
arr2 = np.array([1,2,3])

print(np.dot(arr1, arr2))
# (2 X 1) + (3 X 2) + (4 X 3) = 20

20


In [ ]:
# 2차원 행렬
# dot product (내적 연산)
''' 
< dot product 의 연산 과정 >
[[a, b]   [[e, f]       [[ae + bg, af + bh]   
 [c, d]]   [g, h]]  =>   [ce + dg, cf + dh]]
'''
arr1 = np.array([[1,2],
                 [4,5]])
arr2 = np.array([[1,2],
                 [0,3]])
print(np.dot(arr1, arr2))

[[ 1  8]
 [ 4 23]]


In [ ]:
# 절댓값
arr1 = np.array([[1, -2],
                 [-4,5]])
print(np.abs(arr1))

[[1 2]
 [4 5]]


In [ ]:
# 올림
arr1 = np.array([[1.932, -2.339],
                 [-4.145, 5.206]])
print(np.ceil(arr1))

# 내림
print(np.floor(arr1))

# 반올림
print(np.round(arr1))

# 버림
print(np.trunc(arr1))

[[ 2. -2.]
 [-4.  6.]]
[[ 1. -3.]
 [-5.  5.]]
[[ 2. -2.]
 [-4.  5.]]
[[ 1. -2.]
 [-4.  5.]]
