<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/3-3%20%EB%B0%B0%EC%97%B4%EC%9D%98%20%EC%97%B0%EC%82%B03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1,2,3],
                [0,1,4]])

In [ ]:
# min
print(np.min(arr))
print(arr.min())
print(arr.min(axis=0)) # 열
print(arr.min(axis=1)) # 행

0
0
[0 1 3]
[1 0]


In [ ]:
# max
print(np.max(arr))
print(arr.max())
print(arr.max(axis=0)) # 열
print(arr.max(axis=1)) # 행

4
4
[1 2 4]
[3 4]


In [ ]:
# sum
print(np.sum(arr))
print(arr.sum())
print(arr.sum(axis=0)) # 열
print(arr.sum(axis=1)) # 행

11
11
[1 3 7]
[6 5]


In [ ]:
# mean
print(np.mean(arr))
print(arr.mean())
print(arr.mean(axis=0)) # 열
print(arr.mean(axis=1)) # 행

1.8333333333333333
1.8333333333333333
[0.5 1.5 3.5]
[2.         1.66666667]


In [ ]:
# 표준편차 (분산의 정도를 나타낸 값)
print(np.std(arr))
print(arr.std())
print(arr.std(axis=0)) # 열
print(arr.std(axis=1)) # 행

1.343709624716425
1.343709624716425
[0.5 0.5 0.5]
[0.81649658 1.69967317]


In [ ]:
# 누적값을 계산하는 함수
print(np.cumsum(arr))
print(arr.cumsum())
print(arr.cumsum(axis=0)) # 열
print(arr.cumsum(axis=1)) # 행

[ 1  3  6  6  7 11]
[ 1  3  6  6  7 11]
[[1 2 3]
 [1 3 7]]
[[1 3 6]
 [0 1 5]]


In [ ]:
# 중앙값을 계산하는 함수
# 원소가 짝수일 경우 가장 중앙에 있는 2개값의 사잇값을 반환한다
arr = np.array([[1, 2, 3],
                [0, 1, 4],
                [1, 5, 2]])

print(np.median(arr))
print(np.median(arr, axis=0)) # 열
print(np.median(arr, axis=1)) # 행

2.0
[1. 2. 3.]
[2. 1. 2.]
