<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/5-2%20%EB%B0%B0%EC%97%B4%EC%9D%98%20%ED%98%95%ED%83%9C%20%EB%B3%80%EA%B2%BD2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


resize()!! reshape과 비슷하지만 원본데이터를 변경 한다는 차이점이 있다. 

In [ ]:
# resize, reshape과 비슷하지만 원본데이터를 변경 한다는 차이점이 있다. 
arr.resize(3, 4)
print(arr)

# ravel() : 1차원 배열로 변경해주는 함수
arr = arr.ravel()
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
###############################
## 1차원 배열을 2차원 배열로 만들기 ##
###############################
arr = np.arange(1, 13)
print(arr)
print(arr.ndim)
print("="*40)

# 2차원 배열
arr = arr.reshape(3, -1) # -1 : 을 입력하면 자동으로 -1부분에 들어갈 값이 자동으로 계산된다. 
print(arr)
print(arr.ndim)
print("="*40)

# 3차원 배열
arr = arr.reshape(3, 2, -1)
print(arr)
print(arr.ndim)
print("="*40)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
