<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/6-1%20%EB%B0%B0%EC%97%B4%EC%97%90%20%EC%9B%90%EC%86%8C%20%EC%B6%94%EA%B0%80%20%EB%B0%8F%20%EC%82%AD%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# python list
arr = [1,2,3,4,5,6,7,8]
arr.insert(2, 50)
print(arr)

[1, 2, 50, 3, 4, 5, 6, 7, 8]


In [ ]:
# 1차원 배열
arr = np.arange(1, 9)
arr = np.insert(arr, 2, 50)
print(arr)

[ 1  2 50  3  4  5  6  7  8]


In [ ]:
# 2 차원 배열
arr = np.arange(1, 13).reshape(3, 4)
arr = np.insert(arr, 2, 50, axis=0)
print(arr)
print('='*30)

arr = np.arange(1, 13).reshape(3, 4)
arr = np.insert(arr, 2, 50, axis=1)
print(arr)
print('='*30)

# axis 값을 주지 않으면 1차원 배열로 변형을 한 다음에 값을 삽입한다. 
arr = np.arange(1, 13).reshape(3, 4)
arr = np.insert(arr, 2, 50)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [50 50 50 50]
 [ 9 10 11 12]]
[[ 1  2 50  3  4]
 [ 5  6 50  7  8]
 [ 9 10 50 11 12]]
[ 1  2 50  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# delect() 특정위치의 원소 삭제
arr = np.arange(1, 13).reshape(3, 4)
print(arr)
print('='*30)
arr = np.delete(arr, 2, axis=0)
print(arr)
print('='*30)
arr = np.delete(arr, 2, axis=1)
print(arr)
print('='*30)
arr = np.delete(arr, 2)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 4]
 [5 6 8]]
[1 2 5 6 8]
