<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/6-2%20%EB%B0%B0%EC%97%B4%20%EA%B0%84%EC%9D%98%20%EB%B3%91%ED%95%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# append()  배열의 마지막 부분에 또다른 부분을 추가하는 함수
arr1 = np.arange(1, 13).reshape(3, 4)
arr2 = np.arange(13, 25).reshape(3, 4)

print(arr1)
print("="*20)
print(arr2, end="\n\n")

# axis = 0
arr3 = np.append(arr1, arr2, axis=0)
print(arr3, end="\n\n")

# axis = 1
arr4 = np.append(arr1, arr2, axis=1)
print(arr4, end="\n\n")

# axis = x
arr5 = np.append(arr1, arr2)
print(arr5, end="\n\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]



In [ ]:
# vstack() axis=0을 기준으로 배열을 병합하는 함수
# hstack() axis=1을 기준으로 배열을 병합하는 함수

arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(7, 13).reshape(2, 3)

arr3 = np.vstack((arr1, arr2))
print(arr3)
print("="*30)
arr3 = np.hstack((arr1, arr2))
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
# concatencate() : axis 값을 기준으로 두 배열을 병합하는 함수
arr1 = np.arange(1, 7).reshape(2, 3)
arr2 = np.arange(7, 13).reshape(2, 3)

arr3 = np.concatenate([arr1, arr2], axis=0)
print(arr3, end="\n\n")

arr3 = np.concatenate([arr1, arr2], axis=1)
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
