<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/6-3%20%EB%B0%B0%EC%97%B4%20%EB%B6%84%ED%95%A0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 2차원 배열
arr = np.arange(1, 13).reshape(3, 4)
print(arr, end="\n\n")

# vsplit() : axis=0을 기준으로 분할 행의 갯수대로 할 수 있다.
arr_vsplit = np.vsplit(arr, 3)
print(arr_vsplit, end="\n\n")

# vsplit() : axis=1을 기준으로 분할 열의 갯수대로 할 수 있다.
arr_hsplit = np.hsplit(arr, 2)
print(arr_hsplit, end="\n\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]



In [ ]:
# 3차원 배열
arr = np.random.randint(0, 10, (4, 6 ,8))
print(arr)

[[[2 7 3 5 8 7 0 8]
  [6 3 8 0 2 9 3 6]
  [1 3 0 7 6 1 8 4]
  [2 9 1 6 0 1 5 7]
  [0 3 1 7 0 5 1 9]
  [8 7 4 2 1 7 9 0]]

 [[6 2 7 4 3 3 9 7]
  [1 5 2 1 0 3 6 8]
  [4 9 5 7 1 3 0 6]
  [6 6 1 2 2 5 3 5]
  [3 2 5 7 7 6 5 8]
  [5 0 5 9 0 3 2 7]]

 [[3 7 5 3 9 0 5 8]
  [7 2 6 9 6 3 3 0]
  [0 0 1 7 6 4 0 3]
  [7 7 8 1 2 8 7 2]
  [8 1 0 5 5 2 5 6]
  [7 4 5 0 0 1 9 7]]

 [[8 3 6 5 2 7 5 4]
  [4 1 6 8 6 3 6 5]
  [9 5 0 7 5 4 5 0]
  [1 0 9 8 2 0 4 2]
  [4 1 7 3 2 3 9 8]
  [1 8 3 9 2 2 3 0]]]


In [ ]:
arr_vsplit = np.vsplit(arr, 2)
print(arr_vsplit, end="\n\n")

[array([[[2, 7, 3, 5, 8, 7, 0, 8],
        [6, 3, 8, 0, 2, 9, 3, 6],
        [1, 3, 0, 7, 6, 1, 8, 4],
        [2, 9, 1, 6, 0, 1, 5, 7],
        [0, 3, 1, 7, 0, 5, 1, 9],
        [8, 7, 4, 2, 1, 7, 9, 0]],

       [[6, 2, 7, 4, 3, 3, 9, 7],
        [1, 5, 2, 1, 0, 3, 6, 8],
        [4, 9, 5, 7, 1, 3, 0, 6],
        [6, 6, 1, 2, 2, 5, 3, 5],
        [3, 2, 5, 7, 7, 6, 5, 8],
        [5, 0, 5, 9, 0, 3, 2, 7]]]), array([[[3, 7, 5, 3, 9, 0, 5, 8],
        [7, 2, 6, 9, 6, 3, 3, 0],
        [0, 0, 1, 7, 6, 4, 0, 3],
        [7, 7, 8, 1, 2, 8, 7, 2],
        [8, 1, 0, 5, 5, 2, 5, 6],
        [7, 4, 5, 0, 0, 1, 9, 7]],

       [[8, 3, 6, 5, 2, 7, 5, 4],
        [4, 1, 6, 8, 6, 3, 6, 5],
        [9, 5, 0, 7, 5, 4, 5, 0],
        [1, 0, 9, 8, 2, 0, 4, 2],
        [4, 1, 7, 3, 2, 3, 9, 8],
        [1, 8, 3, 9, 2, 2, 3, 0]]])]



In [ ]:
arr_hsplit = np.hsplit(arr, 2)
print(arr_hsplit)

[array([[[2, 7, 3, 5, 8, 7, 0, 8],
        [6, 3, 8, 0, 2, 9, 3, 6],
        [1, 3, 0, 7, 6, 1, 8, 4]],

       [[6, 2, 7, 4, 3, 3, 9, 7],
        [1, 5, 2, 1, 0, 3, 6, 8],
        [4, 9, 5, 7, 1, 3, 0, 6]],

       [[3, 7, 5, 3, 9, 0, 5, 8],
        [7, 2, 6, 9, 6, 3, 3, 0],
        [0, 0, 1, 7, 6, 4, 0, 3]],

       [[8, 3, 6, 5, 2, 7, 5, 4],
        [4, 1, 6, 8, 6, 3, 6, 5],
        [9, 5, 0, 7, 5, 4, 5, 0]]]), array([[[2, 9, 1, 6, 0, 1, 5, 7],
        [0, 3, 1, 7, 0, 5, 1, 9],
        [8, 7, 4, 2, 1, 7, 9, 0]],

       [[6, 6, 1, 2, 2, 5, 3, 5],
        [3, 2, 5, 7, 7, 6, 5, 8],
        [5, 0, 5, 9, 0, 3, 2, 7]],

       [[7, 7, 8, 1, 2, 8, 7, 2],
        [8, 1, 0, 5, 5, 2, 5, 6],
        [7, 4, 5, 0, 0, 1, 9, 7]],

       [[1, 0, 9, 8, 2, 0, 4, 2],
        [4, 1, 7, 3, 2, 3, 9, 8],
        [1, 8, 3, 9, 2, 2, 3, 0]]])]
