<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/7-1%20%EC%8B%A4%EC%8A%B5%EC%98%88%EC%A0%9C%20%E2%91%A0%20~%20%E2%91%A2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

< 실습예제 1 >
- 원소가 모두 3인 (3,4,5) 형태의 numpy.array를 출력하시오

In [ ]:
arr = np.full((3, 4, 5), 3)
print(arr)

[[[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]

 [[3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]
  [3 3 3 3 3]]]


< 실습 예제 2 >
- 정수 -50 ~ 50의 범위 안의 난수로 이루어진 (4, 5)형태의 numpy.array를 출력하고 행을 기준으로 오름차순 정렬한 결과와 전체 배열을 1차원 배열로 변경하여 오름차순 정렬과 결과를 출력하시오.

In [ ]:
arr = np.random.randint(-50, 50, (4, 5))
print(arr, end="\n\n")

# 행을 기준으로 정렬
print(np.sort(arr, axis=0), end="\n\n")

# 1차원 배열로 변경 axis값 None으로 주기
print(np.sort(arr, axis=None))

[[ -2  25 -22 -39 -28]
 [ 28 -19 -45  25 -43]
 [-34  -9  13 -46 -38]
 [-25 -35 -26 -45 -10]]

[[-34 -35 -45 -46 -43]
 [-25 -19 -26 -45 -38]
 [ -2  -9 -22 -39 -28]
 [ 28  25  13  25 -10]]

[-46 -45 -45 -43 -39 -38 -35 -34 -28 -26 -25 -22 -19 -10  -9  -2  13  25
  25  28]


< 실습예제 3 >
- 다음과 같은 파이썬 list가 존재한다
- list 안에 있는 각 numpy.array의 원소들의 평균값과 표준편차, 중앙값을 순서대로 구하여 구한 순서대로 원소가 이루어진 새로운 list를 구성하고 출력하시오.
- 예시 : 각 배열의 평균값이 3.0, 4.0, 5.0이고 표준편차가 1.5, 1.7, 1.9이며 중앙값이 1.0, 2.0, 3.0 이라면 배열로 구성하여 [3.0, 1.5, 1.0, 4.0, 1.7, 2.0, 5.0, 1.9, 3.0] 으로 출력한다.

py_list = [
    np.full(3, 8),
    np.array([33, -15, 26]),
    np.linspace(17, 26, 3)
]


In [ ]:
py_list = [
    np.full(3, 8),
    np.array([33, -15, 26]),
    np.linspace(17, 26, 3)
]

In [ ]:
result_arr = []
for i in py_list:
  result_arr.append(np.mean(i))
  result_arr.append(np.std(i))
  result_arr.append(np.median(i))

print(result_arr)

[8.0, 0.0, 8.0, 14.666666666666666, 21.171259344267224, 26.0, 21.5, 3.6742346141747673, 21.5]
