<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/7-2%20%EC%8B%A4%EC%8A%B5%EC%98%88%EC%A0%9C%20%E2%91%A3%20~%20%E2%91%A5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

< 실습예제 4 >
- 다음과 같은 numpy.array가 존재한다. 이 배열을 행을 기준으로 3개의 배열로 분할하여 분할된 각 배열의 원소들을 제곱한 결과를 다시 원본 배열에 행을 기준으로 병합하시오. (단, 마지막 출력 결과는 원본 배열과 차원이 같아야 한다)

In [ ]:
arr = np.arange(2, 20, 2).reshape((3, 3))
print(arr)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
# 배열 분할
s1 = np.vsplit(arr, 3)
print(s1)
print("="*30)
# 제곱
s2 = np.square(s1)
print(s2)
print("="*30)
# 차원 축소
s3 = np.squeeze(s2, axis=1)
print(s3)
print("="*30)

result_arr = np.vstack((arr, s3))
print(result_arr)

[array([[2, 4, 6]]), array([[ 8, 10, 12]]), array([[14, 16, 18]])]
[[[  4  16  36]]

 [[ 64 100 144]]

 [[196 256 324]]]
[[  4  16  36]
 [ 64 100 144]
 [196 256 324]]
[[  2   4   6]
 [  8  10  12]
 [ 14  16  18]
 [  4  16  36]
 [ 64 100 144]
 [196 256 324]]


< 실습예제 5 > 
- 삼각함수의 특수각(0deg, 30deg, 60deg, 90deg)을 numpy.array로 생성한 후 특수각에 해당하는 sin, cos, tan 값을 각각 구하여 파이썬 list에 담은 다음 해당 list에 들어있는 값들을 출력하시오. (단, 값이 무한대라면 "INF" 문자열을 출력할 것)
- numpy의 삼각함수는 radian 값을 사용하기 때문에 degree를 radian으로 변경해야합니다.

In [ ]:
# 특수각
arr = np.arange(0, 91, 30)
print(arr)

lst = []
lst.append(np.sin(arr * np.pi / 180))
lst.append(np.cos(arr * np.pi / 180))
lst.append(np.tan(arr * np.pi / 180))

for value_lst in lst:
  for value in value_lst:
    if value > 99999999:
      print("INF")
      continue
    print(value)
  print()

[ 0 30 60 90]
0.0
0.49999999999999994
0.8660254037844386
1.0

1.0
0.8660254037844387
0.5000000000000001
6.123233995736766e-17

0.0
0.5773502691896257
1.7320508075688767
INF



< 실습예제 6 >
- numpy.array를 이용하여 다음과 같은 패턴을 출력하시오. (단, 출력 시 반복문을 사용하여 출력한다)

---


0 1 0 1 0 1 0   
1 0 1 0 1 0 1   
0 1 0 1 0 1 0   
1 0 1 0 1 0 1   
0 1 0 1 0 1 0   
1 0 1 0 1 0 1   
0 1 0 1 0 1 0 

In [ ]:
arr = np.zeros((7, 7), dtype=int)

# 슬라이싱
# 처음부터 끝까지 2step / [::2] = 행
# 첫번째 열부터 끝까지 2step / [1::2] = 열
arr[::2, 1::2] =1 

# 첫번째 행부터 끝까지 2step / [1::2] = 행
# 처음부터 끝까지 2step / [::2] = 열
arr[1::2, ::2] = 1

for row in range(7):
  for col in range(7):
    print(arr[row, col], end="")
  print()

0101010
1010101
0101010
1010101
0101010
1010101
0101010
