<a href="https://colab.research.google.com/github/hyunicecream/Inflearn/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy란

- C언어를 기반으로 내부 반복문을 사용하여 속도가 매우 빠르다.
- 다차원 배열(ndarray)을 편리하게 처리할 수 있도록 지원해주는 파이썬 라이브러리다.

※ ndarray vs list

- ndarray : 적은 메모리로 데이터를 빠르게 처리하고, 모든 원소는 같은 자료형을 가진다.
- list : 속도가 매우 느리고, 원소가 각각 다른 자료형을 가질 수 있다.

### ndarray

- N-dimensional Array
- 다차원 배열을 지원한다.
- 서로 다른 타입의 데이터를 담을 수 없다.
- 내부 반복문을 사용해서 속도가 빠르다.
- 배열 간에 산술 연산이 가능하다.

### 데이터 타입 종류

1. int(8bit, 16bit, 32bit, 64bit) i1, i2, i4, i8
- 부호가 있다.
- 비트수 만큼 크기를 가지는 정수형이다.
- 저장할 수 있는 값의 범위 : -2ⁿ⁻¹ ~ 2ⁿ⁻¹-1
    
    

 2. uint(8bit, 16bit, 32bit, 64bit) u1, u2, u4, u8

- 부호가 없다.
- 비트수 만큼 크기를 가지는 정수형이다.
- 저장할 수 있는 값의 범위 : 0 ~ 2ⁿ-1

 3. float(16bit, 32bit, 64bit, 128bit) f2, f4, f8, f16

- 부호가 있다.
- 비트수 만큼 크기를 가지는 실수형이다.

 4. 복소수형

- complex64 : 두개의 32비트 부동 소수점으로 표시되는 복소수 c8
- complex128 : 두개의 64비트 부동소수점으로 표시되는 복소수 c16

 5. unicode

- 고정 길이 문자열 unicode

 6. bool

- True, False

 7. 데이터 타입 확인 및 변경

- dtype : 자료형 확인
- astype : 자료형 변경

In [ ]:
import numpy as np

In [ ]:
data = [[1,2,3], [4,5,6], [7,8,9]]

a = np.array(data)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
type(a)

numpy.ndarray

In [ ]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [ ]:
# 형변환
a = a.astype(np.float32) # a = a.astype('float32')
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [ ]:
a[0][1] # a의 0번째의 1번째

2.0

In [ ]:
a[0]

array([1., 2., 3.], dtype=float32)

- np.arange(start, stop, step) : step에 따라 증가하는 수열을 생성한다.
- reshape : 만들어진 배열의 데이터를 그대로 가지고 형태를 바꿔준다.

In [ ]:
np.arange(1, 10, 2) # start , stop, step

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1, 13).reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.arange(1, 13).reshape(3, 2, 2) 

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

NaN
- 자료형이 Float형이므로 Integer에서는 오류가 발생한다.
- 배열에서 연산할 경우 오류가 발생하지 않지만  결과값이 NaN이 된다.

In [ ]:
# 결측치
np.nan + 10 
np.nan * 10

nan

In [ ]:
a[0][1] = np.nan
a

array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [ ]:
a = np.arange(1, 10).reshape(3, 3)
a
# int형에서는 nan을 사용x, float에서만 nan 사용가능

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a = np.linspace(1, 10, 20) # 초기값, 종료값, 몇개
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

**연산**

- 반복문을 사용하지 않아도,  배열의 모든 원소는 반복연산이 사용된다.
- 선형 대수 식을 사용하여 연산 가능하다.
    - np.dot, @ : 행렬 곱 구하는 연산

In [ ]:
#########
## 연산 ##
#########
data = np.arange(1, 10).reshape(3, 3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
data * data

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
data / data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 행렬의 곱
np.dot(data, data)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
data@data

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

**차원**

- 0차원 : Scalar (하나의 데이터 값으로만 존재하는 것)
- 1차원 : Vector (숫자들의 배열 (1D array))
- 2차원 : Matrix (숫자들의 2D array (rows: 행, columns: 열))
- 3차원 이상 : Tensor (숫자들의 다차원 배열)

In [ ]:
##############
#### 차원 #####
##############

In [ ]:
# 0차원 : 스칼라
a = np.array(1)
a
a.shape
a.ndim # 차원

0

In [ ]:
# 1차원 : 벡터
a = np.array([1])
a
a.shape
a.ndim # 차원

array([1])

In [ ]:
# 1차원 : 스칼라
a = np.array([1,2,3,4,5])
a
a.shape 
a.ndim # 차원

1

In [ ]:
# 2차원 : 메트릭스
a = np.array([[1,2,3], [4,5,6]])
a
a.shape 
a.ndim # 차원

2

In [ ]:
# 3차원 : 3차원 이상의 다차원의 행렬을 Tensor
a = np.array([[[1,2], [3,4], [5,6]], [[7,8], [9,10], [11,12]]])
a
a.shape 
a.ndim # 차원

3

**Matrix 유형**

- zeros : 0으로 초기화된 배열 생성
- ones  : 1로 초기화 된 배열 생성
- eye : 주대각선의 원소가 모두 1이고 나머지 원소는 0인 정사각행렬 (단위행렬)
- empty : 초기화 하지 않고 배열만 생성, 기존에 메모리에 저장되어 있는 값으로 나타남
- full : 지정한 숫자로 초기화
- linespace(start, end(포함), number, endpoint = ) : 선형 구간을 지정한 개수만큼 분할한다.
    - endpoint = True or False : 마지막 값을 포함시킬지 시키지 않을지 선택

In [ ]:
###############
### Martix의 유형
###############

In [ ]:
a = np.arange(12).reshape(2, 3, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [ ]:
b = np.ones(12).reshape(2, 3, 2)
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
c = np.zeros(12).reshape(2,3,2)
c

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
# 단위행렬 자신과 곱했을때 자신이 나오도록
d = np.eye(3) # 단위행렬 3,3
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
c = np.zeros(12).reshape([3, 4])
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
f = np.empty([2,3])
f

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [ ]:
g = np.full((3, 4), 1000)
g

array([[1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000]])

In [ ]:
h = np.linspace(2, 10, 6)
h

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

**집계함수**

- mean : 평균을 구하는 함수
- median : 데이터를 크기로 정렬하고 그 중 가운데 수 출력하는 함수
    
    ※ 만약 데이터 개수가 짝수일 경우 가장 가운데의 두 수의 평균을 구한다.
    
- var : 분산 구하는 함수
- std : 표준편차 구하는 함수
- sum : 합계 구하는 함수
- max : 가장 큰 수를 구하는 함수
- min : 가장 작은 수를 구하는 함수

In [ ]:
####################
###### 집계함수 ######
####################

In [ ]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a[0][0] = 100
a

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9]])

In [ ]:
a[0, 1] = 1000
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [ ]:
np.mean(a) # 평균

114.4

In [ ]:
np.median(a) # 중아값

6.5

In [ ]:
np.std(a) # 표준편차

296.5485457728633

296.5485457728633

In [ ]:
np.var(a) # 분산

87941.04

In [ ]:
np.sum(a)

1144

In [ ]:
sum(a)

array([ 105, 1006,    9,   11,   13])

In [ ]:
a

array([[ 100, 1000,    2,    3,    4],
       [   5,    6,    7,    8,    9]])

In [ ]:
np.sum(a, axis=0) # col으로 덧셈

array([ 105, 1006,    9,   11,   13])

In [ ]:
np.sum(a, axis=1) # row 로 덧셈

array([1109,   35])

In [ ]:
np.max(a)

1000

In [ ]:
np.min(a)

2